version: 0.2
phases:
  install:
    commands:
      - composer install --dev
      - composer global require phpunit/phpunit
  build:
    commands:
      - composer format
      - composer lint
      - composer lint:fix  
      - composer test  
