version: 0.2

env:
  variables:
    SODIUM_CRYPTO_SECRETBOX_KEY: b49cb41a2cff8db4f99ea27c7d80a4073337108c228535da506970fd1fbc34e8
    JWT_SECRET: batata

phases:
  install:
    commands:
      - echo "Instalando dependências do sistema..."
      - apt-get update
      - apt-get install -y libsodium-dev zip git unzip libxml2-dev libicu-dev
      - pecl install sodium
      - echo "extension=sodium.so" > /etc/php/7.4/cli/conf.d/40-sodium.ini
      - composer install --dev 
  build:
    commands:   
      - php -m | grep sodium
      - php -r "if (function_exists('sodium_crypto_secretbox')) { echo 'Sodium está funcionando!'; } else { echo 'Sodium NÃO está disponível!'; }"   
      - composer format
      - composer lint
      - composer lint:fix  
      - composer test  
