services:

  nginx:
    image: nginx:1.29.1
    container_name: gamebase-backend-nginx
    volumes:   
      - ./nginx.conf:/etc/nginx/conf.d/default.conf    
      - ./:/var/www/html
    ports:
      - "${NGINX_EXPOSE_PORT}:${NGINX_PORT}"
    depends_on:
      - php
      - mariadb
      - redis
    networks:
      - gamebase-backend-network      

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gamebase-backend-php
    volumes:
      - ./:/var/www/html
    networks:
      - gamebase-backend-network      
      
  redis:
    container_name: gamebase-backend-redis
    image: redis:8.2.1
    volumes:
      - redis_data:/data
    ports:
      - "${REDIS_EXPOSE_PORT}:${REDIS_PORT}"
    networks:
      - gamebase-backend-network      

  mariadb:
    container_name: gamebase-backend-mariadb
    image: mariadb:12.0.2
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - ${REPOSITORY_EXPOSE_PORT}:${REPOSITORY_PORT}
    networks:
      - gamebase-backend-network
    environment:
      - MARIADB_ROOT_PASSWORD=${REPOSITORY_ROOT_PASSWORD}
      - MARIADB_DATABASE=${REPOSITORY_DATABASE}
      - MARIADB_USER=${REPOSITORY_USERNAME}
      - MARIADB_PASSWORD=${REPOSITORY_PASSWORD}      

volumes:
  mariadb_data:      
  redis_data:

networks:
  gamebase-backend-network:
    driver: bridge