name: Deploy PHP App to AWS EC2

on:
  push:
    branches:
      - dev  # Roda o deploy quando houver push na branch dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar chave SSH
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: Deploy para EC2 via SSH
        run: |
          ssh -i private_key.pem -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
            cd /var/www/html
            sudo rm -rf gamebase-backend
            sudo mkdir gamebase-backend
            cd gamebase-backend
            sudo git clone https://github.com/mvreisg/gamebase-backend.git
            sudo chown -R www-data:www-data /var/www/html/gamebase-backend
            sudo chmod -R 755 /var/www/html/gamebase-backend
          EOF
